version: '3'
services:
  # laravel
  laravel:
    build:
      context: ./src
      dockerfile: ../config/laravel/Dockerfile
    image: digitalocean.com/php
    container_name: laravel
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: laravel
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./src/:/var/www
    networks:
      - laranet

  # Nginx Backend Service
  laravel-webserver:
    image: nginx:alpine
    container_name: laravel-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8085:80"
    volumes:
      - ./src/:/var/www
      - ./config/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laranet
    
  # Database
  laravel-database:
    image: mysql:8.3.0
    volumes:
      - laravel-dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: example
      MYSQL_ROOT_PASSWORD: example
      MYSQL_PASSWORD: example
      MYSQL_USER: example
    ports:
      - 33065:3306
    networks:
      - laranet


# Docker Network
networks:
  laranet:
    driver: bridge

volumes:
  laravel-dbdata:

